// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxdlqiwojidrfnapawmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4ZGxxaXdvamlkcmZuYXBhd21pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzOTMwODUsImV4cCI6MjA3Mzk2OTA4NX0.jEcUeujnVdcXguZLoKTTX1LYbb1Pud0Qf8pMORwurTM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});